import type { BoardColumn, ChatMessage } from "./taskBoard.types.ts";

const commonDescription = "Create content for peceland App";

export const boardColumns: BoardColumn[] = [
  {
    id: "backlog",
    title: "Backlog",
    tasks: [
      {
        id: 1,
        title: "Create styleguide foundation",
        description: commonDescription,
        category: "Design",
        date: "Aug 20, 2021",
        image: "/images/tasks/task-blue.jpg",
        completed: 0,
        total: 8,
        members: ["AN", "CH", "JM"],
      },
      {
        id: 2,
        title: "Copywriting Content",
        description: commonDescription,
        category: "Research",
        date: "Aug 20, 2021",
        completed: 0,
        total: 8,
        members: ["AN", "CH"],
      },
      {
        id: 3,
        title: "Update requiment list",
        description: commonDescription,
        category: "Planning",
        date: "Sep 20, 2021",
        comments: 4,
        files: 11,
        members: [],
      },
    ],
  },
  {
    id: "todo",
    title: "To Do",
    tasks: [
      {
        id: 4,
        title: "auditing information architecture",
        description: commonDescription,
        category: "Research",
        date: "Aug 20, 2021",
        comments: 4,
        files: 11,
        members: [],
      },
      {
        id: 5,
        title: "Update support documentation",
        description: commonDescription,
        category: "Content",
        date: "Aug 16, 2021",
        image: "/images/tasks/task-colorful.jpg",
        completed: 0,
        total: 8,
        members: ["AN", "CH", "JM"],
      },
      {
        id: 6,
        title: "Qualitative research planning",
        description: commonDescription,
        category: "Research",
        date: "Aug 20, 2021",
        completed: 0,
        total: 8,
        members: ["AN", "CH"],
      },
    ],
  },
  {
    id: "progress",
    title: "In Progress",
    tasks: [
      {
        id: 7,
        title: "Listing deliverables checklist",
        description: commonDescription,
        category: "Planning",
        date: "Sep 20, 2021",
        comments: 4,
        files: 11,
        members: [],
      },
      {
        id: 8,
        title: "Qualitative research planning",
        description: commonDescription,
        category: "Research",
        date: "Aug 20, 2021",
        completed: 0,
        total: 8,
        members: ["AN", "CH"],
      },
      {
        id: 9,
        title: "Copywriting Content",
        description: commonDescription,
        category: "Design",
        date: "Aug 20, 2021",
        image: "/images/tasks/task-orange.jpg",
        completed: 0,
        total: 8,
        members: ["AN", "CH", "JM"],
      },
    ],
  },
  {
    id: "review",
    title: "Review",
    tasks: [
      {
        id: 10,
        title: "Design System",
        description: commonDescription,
        category: "Content",
        date: "Aug 16, 2021",
        image: "/images/tasks/task-waves.jpg",
        completed: 0,
        total: 8,
        members: ["AN", "CH"],
      },
      {
        id: 11,
        title: "High fedality UI Desktop",
        description: commonDescription,
        category: "Design",
        date: "Aug 20, 2021",
        completed: 0,
        total: 8,
        members: ["AN", "CH"],
      },
      {
        id: 12,
        title: "Listing deliverables checklist",
        description: commonDescription,
        category: "Content",
        date: "Sep 20, 2021",
        comments: 4,
        files: 11,
        members: [],
      },
    ],
  },
];

export const boardMembers = ["AN", "CH", "JM", "AM", "RK", "DS", "MK", "VL", "AR", "KS"];

export const chatMessages: ChatMessage[] = [
  {
    id: 1,
    author: "Chris",
    avatar: "CH",
    text: "Hello! 👋",
    time: "08:00 am",
  },
  {
    id: 2,
    author: "Me",
    avatar: "AN",
    text: "Hi, Everyone 👋",
    time: "08:01 am",
    isOwn: true,
  },
  {
    id: 3,
    author: "Jason",
    avatar: "JM",
    text: "How are you, What did you do everyone",
    time: "08:03 am",
  },
  {
    id: 4,
    author: "Chris",
    avatar: "CH",
    text: "Good ✌",
    time: "08:05 am",
  },
  {
    id: 5,
    author: "Jason",
    avatar: "JM",
    time: "08:08 am",
    audio: true,
  },
];
