import type { Project, ProjectMember } from "@/entities/project";

const members = {
  angelina: {
    id: 1,
    name: "Angelina",
    initials: "AN",
  },
  chris: {
    id: 2,
    name: "Chris",
    initials: "CH",
  },
  jason: {
    id: 3,
    name: "Jason",
    initials: "JM",
  },
  novita: {
    id: 4,
    name: "Novita",
    initials: "NW",
  },
  aditya: {
    id: 5,
    name: "Aditya",
    initials: "AD",
  },
} satisfies Record<string, ProjectMember>;

export const projects: Project[] = [
  {
    id: 1,
    title: "Mobile Banking App",
    description: "Design and development of a new mobile banking application.",
    status: "active",
    color: "purple",
    memberCount: 3,
    tasksCompleted: 18,
    tasksTotal: 25,
    dueDate: "Aug 24, 2026",
    members: [members.angelina, members.chris, members.jason],
  },
  {
    id: 2,
    title: "Website Redesign",
    description: "Redesign the company website and update the visual identity.",
    status: "active",
    color: "blue",
    memberCount: 4,
    tasksCompleted: 12,
    tasksTotal: 25,
    dueDate: "Sep 10, 2026",
    members: [members.angelina, members.novita, members.aditya, members.chris],
  },
  {
    id: 3,
    title: "CRM Dashboard",
    description: "Build an analytics dashboard for customer and sales management.",
    status: "completed",
    color: "green",
    memberCount: 3,
    tasksCompleted: 32,
    tasksTotal: 32,
    dueDate: "Jul 28, 2026",
    members: [members.jason, members.chris, members.novita],
  },
  {
    id: 4,
    title: "Marketing Campaign",
    description: "Prepare campaign materials, landing pages and social media content.",
    status: "active",
    color: "orange",
    memberCount: 2,
    tasksCompleted: 15,
    tasksTotal: 24,
    dueDate: "Aug 30, 2026",
    members: [members.novita, members.aditya],
  },
  {
    id: 5,
    title: "Design System",
    description: "Create reusable UI components, tokens and documentation.",
    status: "on-hold",
    color: "red",
    memberCount: 2,
    tasksCompleted: 9,
    tasksTotal: 26,
    dueDate: "Oct 12, 2026",
    members: [members.angelina, members.chris],
  },
  {
    id: 6,
    title: "E-commerce Platform",
    description: "Develop product catalog, checkout flow and seller management.",
    status: "active",
    color: "purple",
    memberCount: 4,
    tasksCompleted: 26,
    tasksTotal: 32,
    dueDate: "Sep 02, 2026",
    members: [members.jason, members.aditya, members.chris, members.novita],
  },
];
