import type { Conversation } from "@/entities/conversation";

export const conversations: Conversation[] = [
  {
    id: 1,
    name: "Killan James",
    preview: "Typing...",
    time: "4:30 PM",
    avatar: "/images/users/killan.jpg",
    unread: 2,
    isOnline: true,
    isTyping: true,
  },
  {
    id: 2,
    name: "Design Team",
    preview: "Hello! Everyone",
    time: "9:36 AM",
    avatar: "/images/users/design-team.jpg",
    isRead: true,
  },
  {
    id: 3,
    name: "Ahmed Medi",
    preview: "Wow really Cool 🔥",
    time: "1:15 AM",
    avatar: "/images/users/ahmed.jpg",
  },
  {
    id: 4,
    name: "Claudia Maudi",
    preview: "Typing...",
    time: "4:30 PM",
    avatar: "/images/users/claudia.jpg",
    isTyping: true,
  },
  {
    id: 5,
    name: "Novita",
    preview: "yah, nice design",
    time: "4:30 PM",
    avatar: "/images/users/novita.jpg",
    unread: 2,
    isOnline: true,
  },
  {
    id: 6,
    name: "Milie Nose",
    preview: "Awesome 🔥",
    time: "8:20 PM",
    avatar: "/images/users/milie.jpg",
    unread: 1,
    isOnline: true,
  },
  {
    id: 7,
    name: "Ikhsan SD",
    preview: "Voice message",
    time: "Yesterday",
    avatar: "/images/users/ikhsan.jpg",
    isVoice: true,
  },
  {
    id: 8,
    name: "Aditya",
    preview: "Publish now",
    time: "Yesterday",
    avatar: "/images/users/aditya.jpg",
    isRead: true,
    isOnline: true,
  },
  {
    id: 9,
    name: "Ahmed Medi",
    preview: "Wow really Cool 🔥",
    time: "1:15 AM",
    avatar: "/images/users/ahmed.jpg",
  },
];
